# generated by datamodel-codegen:
#   filename:  agent_io.json
#   timestamp: 2026-05-07T17:23:27+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    constr,
)


class AgentIO(RootModel[Any]):
    root: Any = Field(
        ...,
        description="Per-agent INPUT contracts. Outputs are 'findings' defined in reasoning.json (cross-file $ref). When implementing each agent (OpenAI Agents SDK structured output), use these as the input contract and the corresponding finding schema as the response_format.\n\nMapping (input → output):\n- ClassifierInput → ClassifierOutput (defined here, consumed by perception.json content.category)\n- CoordinatorInput → CoordinatorOutput (defined here, consumed by services/orchestrator.py for parallel L2 dispatch)\n- PersuasionAgentInput → reasoning.json#/$defs/PersuasionFinding\n- FactCheckAgentInput → reasoning.json#/$defs/FactCheckFinding\n- ProvenanceAgentInput → reasoning.json#/$defs/ProvenanceFinding\n- CounterPerspectiveAgentInput → reasoning.json#/$defs/CounterPerspectiveFinding\n\nCoordinator is an LLM agent (CLAUDE.md decision #5) using reasoning_effort=low, NOT Python orchestration. Its output drives parallel L2 worker dispatch.",
        title="AgentIO",
    )


class AgentInputBase(BaseModel):
    session_id: UUID = Field(
        ..., description="Browser tab session UUID (carried from perception.json)."
    )
    content_id: constr(min_length=1) = Field(
        ..., description="Stable per-content-unit ID (carried from perception.json)."
    )


class ClassifierInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    content_id: constr(min_length=1)
    text: str = Field(..., description="Visible text to classify.")
    image_urls: list[AnyUrl] | None = Field(
        [],
        description="Optional. If model supports vision, lets classifier consider image cues (e.g., meme format, ad layout).",
    )


class Category(StrEnum):
    news = "news"
    ad = "ad"
    health_claim = "health_claim"
    social = "social"
    meme = "meme"
    unknown = "unknown"


class ClassifierOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: Category = Field(..., description="See ENUMS.md → ContentCategory.")
    confidence: confloat(ge=0.0, le=1.0)


class CoordinatorInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    content_id: constr(min_length=1)
    category: Category
    category_confidence: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description="L1 Classifier confidence. Coordinator overrides skip rules when this is low (< 0.5) — dispatch ALL workers as safe default.",
    )


class DispatchableAgent(StrEnum):
    persuasion = "persuasion"
    fact_check = "fact_check"
    provenance = "provenance"


class SkippedAgent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent: DispatchableAgent
    reason: constr(min_length=1) = Field(
        ...,
        description="1-line specific justification, e.g., 'meme — no factual claim to verify'.",
    )


class CoordinatorOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dispatched_agents: list[DispatchableAgent] = Field(
        ..., description="Workers to invoke in parallel."
    )
    skipped_agents: list[SkippedAgent] = Field(
        ...,
        description="Workers to skip, with reasons. Empty array if all are dispatched.",
    )


class PersuasionAgentInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    content_id: constr(min_length=1)
    text: str = Field(
        ...,
        description="Full visible text. Persuasion Agent quotes spans from this as evidence.",
    )
    category: Category = Field(
        ...,
        description="Helps prompt narrow which tactic patterns are most likely (e.g., 'ad' → emphasize Cialdini scarcity/authority; 'health_claim' → emphasize fear_mongering, misrepresentation_of_expertise).",
    )


class Category3(StrEnum):
    news = "news"
    ad = "ad"
    health_claim = "health_claim"
    social = "social"
    unknown = "unknown"


class FactCheckAgentInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    content_id: constr(min_length=1)
    text: str = Field(
        ...,
        description="Full visible text. Agent extracts atomic claims from this and verifies each.",
    )
    category: Category3 = Field(
        ...,
        description="Coordinator will not dispatch Fact-Check for category='meme'. Other categories pass through; agent itself returns 'not_a_claim' for opinion-only content.",
    )
    url: AnyUrl | None = Field(
        None,
        description="Page URL — sometimes hints at topic (e.g., 'who.int/...' suggests authoritative health source).",
    )


class SyntheticSignals(BaseModel):
    ai_text_prob: confloat(ge=0.0, le=1.0) | None = None
    ai_image_prob: confloat(ge=0.0, le=1.0) | None = None
    c2pa_present: bool | None = None
    c2pa_verified: bool | None = None


class Reputation(StrEnum):
    credible = "credible"
    mixed = "mixed"
    unreliable = "unreliable"
    unknown = "unknown"


class Source(BaseModel):
    domain: str
    reputation: Reputation


class ProvenanceAgentInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    content_id: constr(min_length=1)
    text_excerpt: constr(max_length=500) = Field(
        ...,
        description="Short excerpt (≤500 chars) — Provenance reasons over signals not full content. Long text is wasted tokens here.",
    )
    synthetic_signals: SyntheticSignals = Field(
        ...,
        description="Carried from perception.json#/properties/synthetic_signals. Agent must handle missing fields (e.g., ai_image_prob absent if no images, c2pa fields absent if not detected).",
    )
    source: Source


class Category4(StrEnum):
    news = "news"
    ad = "ad"
    health_claim = "health_claim"
    social = "social"
    meme = "meme"
    unknown = "unknown"


class Tactic(StrEnum):
    reciprocation = "reciprocation"
    commitment_consistency = "commitment_consistency"
    social_proof = "social_proof"
    liking = "liking"
    authority = "authority"
    scarcity = "scarcity"
    manipulative_emotional_appeals = "manipulative_emotional_appeals"
    false_scarcity = "false_scarcity"
    deceptive_information = "deceptive_information"
    bait_and_switch = "bait_and_switch"
    exploitative_cult_tactics = "exploitative_cult_tactics"
    guilt_tripping = "guilt_tripping"
    fear_mongering = "fear_mongering"
    pressure_and_coercion = "pressure_and_coercion"
    exploiting_vulnerable_individuals = "exploiting_vulnerable_individuals"
    creating_dependency = "creating_dependency"
    misrepresentation_of_expertise = "misrepresentation_of_expertise"
    social_isolation = "social_isolation"
    overwhelming_information = "overwhelming_information"
    playing_on_identity = "playing_on_identity"
    financial_exploitation = "financial_exploitation"


class TacticsDetectedItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tactic: Tactic = Field(
        ...,
        description="One of 21 values from ENUMS.md → PersuasionTactic. Verbatim labels.",
    )
    evidence: str = Field(
        ..., description="Quoted span from the content that triggered this tactic."
    )
    confidence: confloat(ge=0.0, le=1.0)


class PersuasionFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tactics_detected: list[TacticsDetectedItem]
    intended_action: str = Field(
        ...,
        description="What the content is trying to get the user to do (e.g., 'buy supplement', 'share post', 'distrust vaccines').",
    )
    hidden_agenda: str | None = Field(
        None,
        description="Inferred motive beyond the surface ask, if any (e.g., 'affiliate revenue', 'political mobilization'). null if unclear.",
    )


class AgentName(StrEnum):
    coordinator = "coordinator"
    classifier = "classifier"
    persuasion = "persuasion"
    fact_check = "fact_check"
    provenance = "provenance"
    counter = "counter"


class EventBase(BaseModel):
    type: str
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime


class Band(StrEnum):
    safe = "safe"
    caution = "caution"
    high_risk = "high_risk"


class ContributingFactor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    factor: str = Field(
        ...,
        description="Human-readable factor (e.g., 'Fear-mongering tactic detected', 'Source rated unreliable').",
    )
    weight: confloat(ge=-1.0, le=1.0) = Field(
        ..., description="Signed contribution to score (negative reduces score)."
    )


class SovereigntyScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: confloat(ge=0.0, le=100.0) = Field(
        ..., description="Sovereignty score. Higher = lower manipulation risk."
    )
    band: Band = Field(
        ...,
        description="See ENUMS.md → ScoreBand. Derived from value (70-100 safe, 30-69 caution, 0-29 high_risk).",
    )
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description="Coordinator's confidence in this score (lowered when agents disagree or returned errors).",
    )
    contributing_factors: list[ContributingFactor] | None = Field(
        None,
        description="Top reasons for the score, ordered by weight. Used by 'Ask why' modal.",
    )


class Verdict(StrEnum):
    supported = "supported"
    contradicted = "contradicted"
    unverifiable = "unverifiable"
    not_a_claim = "not_a_claim"


class Source1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    url: AnyUrl
    publisher: str | None = Field(None, description="WHO, CDC, Mayo Clinic, etc.")
    snippet: str | None = Field(None, description="Quoted relevant fragment from the source.")


class Claim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim: str = Field(..., description="Atomic factual claim extracted from content.")
    verdict: Verdict = Field(..., description="See ENUMS.md → FactCheckVerdict.")
    explanation: str | None = Field(None, description="Brief reason for the verdict.")
    sources: list[Source1] | None = Field(
        None,
        description="RAG-retrieved sources backing the verdict. Empty for 'not_a_claim'.",
    )


class FactCheckFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claims: list[Claim] = Field(
        ...,
        description="Each factual claim extracted from the content, verified independently.",
    )


class SyntheticVerdict(StrEnum):
    likely_human = "likely_human"
    uncertain = "uncertain"
    likely_ai = "likely_ai"


class SourceVerdict(StrEnum):
    credible = "credible"
    mixed = "mixed"
    unreliable = "unreliable"
    unknown = "unknown"


class ProvenanceFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    synthetic_verdict: SyntheticVerdict = Field(..., description="See ENUMS.md → SyntheticVerdict.")
    source_verdict: SourceVerdict = Field(
        ...,
        description="Provenance Agent may upgrade or downgrade the L1 hardcoded reputation based on cross-referencing.",
    )
    reasoning: str = Field(
        ...,
        description="1-2 sentence rationale explaining the verdicts. Surfaced in 'Ask why' modal.",
    )


class Credibility(StrEnum):
    credible = "credible"
    mixed = "mixed"
    unreliable = "unreliable"
    unknown = "unknown"


class AlternativeSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl
    title: str
    publisher: str | None = None
    credibility: Credibility | None = None


class CounterPerspectiveFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    steelman: str = Field(
        ...,
        description="Best-faith opposing view to the content's claim, written as a coherent argument the user can engage with.",
    )
    alternative_sources: list[AlternativeSource] | None = Field(
        None, description="Higher-credibility sources offering a different angle."
    )


class SkippedAgent1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent: AgentName
    reason: str


class ReasoningState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: SovereigntyScore
    dispatched_agents: list[AgentName] = Field(
        ..., description="Which L2 agents Coordinator decided to run for this content."
    )
    skipped_agents: list[SkippedAgent1] | None = Field(
        None,
        description="Agents Coordinator deliberately skipped, with reason (e.g., 'meme → skip Fact-Check').",
    )
    persuasion: PersuasionFinding | None = None
    fact_check: FactCheckFinding | None = None
    provenance: ProvenanceFinding | None = None
    counter: CounterPerspectiveFinding | None = None


class SkippedAgent2(BaseModel):
    agent: AgentName
    reason: str


class CoordinatorDispatchedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["coordinator_dispatched"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    dispatched_agents: list[AgentName]
    skipped_agents: list[SkippedAgent2] | None = None


class AgentStartedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["agent_started"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    agent: AgentName


class AgentFinishedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["agent_finished"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    agent: AgentName
    finding: (
        PersuasionFinding | FactCheckFinding | ProvenanceFinding | CounterPerspectiveFinding
    ) = Field(
        ...,
        description="Concrete shape depends on agent: persuasion → PersuasionFinding, fact_check → FactCheckFinding, provenance → ProvenanceFinding, counter → CounterPerspectiveFinding.",
    )


class ScoreUpdateEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["score_update"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    score: SovereigntyScore


class FinalEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["final"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    state: ReasoningState


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        description="Stable error code (e.g., 'llm_timeout', 'rag_unavailable', 'invalid_input').",
    )
    message: str = Field(
        ...,
        description="Human-readable message. Safe to show in dev UI; production UI should map by code.",
    )


class ErrorEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["error"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    agent: AgentName | None = Field(
        None, description="If error is scoped to one agent. Omit for global errors."
    )
    error: Error


class PriorFindings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    persuasion: PersuasionFinding | None = None
    fact_check: FactCheckFinding | None = None
    provenance: ProvenanceFinding | None = None


class CounterPerspectiveAgentInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    content_id: constr(min_length=1)
    text: str
    category: Category4
    prior_findings: PriorFindings | None = Field(
        None,
        description="Findings from earlier-completing agents. Coordinator passes whatever is available when Counter is dispatched. All optional — agent degrades gracefully (writes general-purpose steelman if no prior findings).",
    )
