# generated by datamodel-codegen:
#   filename:  perception.json
#   timestamp: 2026-05-07T17:23:24+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Category(StrEnum):
    news = "news"
    ad = "ad"
    health_claim = "health_claim"
    social = "social"
    meme = "meme"
    unknown = "unknown"


class Content(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str = Field(
        ...,
        description="Visible text of the post. Required even if empty (e.g., image-only post → empty string).",
    )
    images: list[AnyUrl] | None = Field(
        [],
        description="URLs of images in the post (in DOM order). Empty array if no images.",
    )
    category: Category = Field(
        ...,
        description="Output of Content Classifier Agent (L1). See shared/ENUMS.md → ContentCategory.",
    )
    category_confidence: confloat(ge=0.0, le=1.0) | None = Field(
        None,
        description="Classifier confidence in the category (0..1). Used by Coordinator to decide when to fall through to all-agent dispatch on low confidence.",
    )


class SyntheticSignals(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ai_text_prob: confloat(ge=0.0, le=1.0) | None = Field(
        None,
        description="Probability the text is AI-generated (perplexity-based or HF detector).",
    )
    ai_image_prob: confloat(ge=0.0, le=1.0) | None = Field(
        None,
        description="Highest AI-gen probability across images in the post (single number — Provenance Agent decides aggregation).",
    )
    c2pa_present: bool | None = Field(
        None,
        description="Whether ANY image in the post carries C2PA Content Credentials metadata.",
    )
    c2pa_verified: bool | None = Field(
        None,
        description="Whether the C2PA chain validates as human-captured (only meaningful if c2pa_present is true).",
    )


class Reputation(StrEnum):
    credible = "credible"
    mixed = "mixed"
    unreliable = "unreliable"
    unknown = "unknown"


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    domain: constr(min_length=1) = Field(
        ...,
        description="eTLD+1 normalized hostname of the page (e.g., 'example.com' not 'www.example.com').",
    )
    reputation: Reputation = Field(
        ...,
        description="From hardcoded list in data/source_reputation/. See shared/ENUMS.md → SourceReputation.",
    )


class UserState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scroll_velocity_px_per_sec: confloat(ge=0.0) | None = Field(
        None, description="Rolling-average scroll speed when this content was captured."
    )
    dwell_ms: conint(ge=0) | None = Field(
        None,
        description="Milliseconds the content was visible in viewport before perception was triggered.",
    )


class PerceptionPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID = Field(
        ...,
        description="Browser tab session UUID. Used to subscribe to SSE stream and to bind reasoning updates back to the originating tab. One tab = one session.",
    )
    content_id: constr(min_length=1) = Field(
        ...,
        description="Stable ID for one content unit within the session — hash of content text + URL fragment recommended. A 'content unit' is defined by scraper.ts per site type: 1 tweet on Twitter, 1 post on IG, 1 article on news sites, 1 AI message on ChatGPT, etc. Used by L2 to dedupe and by L3 to bind reasoning back to the right DOM element.",
    )
    url: AnyUrl = Field(..., description="Full URL of the page hosting the content.")
    captured_at: AwareDatetime = Field(
        ...,
        description="ISO 8601 timestamp when the extension captured this perception.",
    )
    content: Content
    synthetic_signals: SyntheticSignals | None = Field(
        None,
        description="Output of in-browser ML detectors. Optional — extension may omit fields if a detector hasn't loaded. Provenance Agent in L2 must handle missing fields gracefully.",
    )
    source: Source
    user_state: UserState | None = Field(
        None,
        description="Behavioral context. Optional. Per architecture.md, used as gating signal for annotation aggressiveness — NEVER primary detection.",
    )
