# generated by datamodel-codegen:
#   filename:  reasoning.json
#   timestamp: 2026-05-07T17:23:26+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    constr,
)


class AgentName(StrEnum):
    coordinator = "coordinator"
    classifier = "classifier"
    persuasion = "persuasion"
    fact_check = "fact_check"
    provenance = "provenance"
    counter = "counter"


class EventBase(BaseModel):
    type: str
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime


class Band(StrEnum):
    safe = "safe"
    caution = "caution"
    high_risk = "high_risk"


class ContributingFactor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    factor: str = Field(
        ...,
        description="Human-readable factor (e.g., 'Fear-mongering tactic detected', 'Source rated unreliable').",
    )
    weight: confloat(ge=-1.0, le=1.0) = Field(
        ..., description="Signed contribution to score (negative reduces score)."
    )


class SovereigntyScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: confloat(ge=0.0, le=100.0) = Field(
        ..., description="Sovereignty score. Higher = lower manipulation risk."
    )
    band: Band = Field(
        ...,
        description="See ENUMS.md → ScoreBand. Derived from value (70-100 safe, 30-69 caution, 0-29 high_risk).",
    )
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description="Coordinator's confidence in this score (lowered when agents disagree or returned errors).",
    )
    contributing_factors: list[ContributingFactor] | None = Field(
        None,
        description="Top reasons for the score, ordered by weight. Used by 'Ask why' modal.",
    )


class Tactic(StrEnum):
    reciprocation = "reciprocation"
    commitment_consistency = "commitment_consistency"
    social_proof = "social_proof"
    liking = "liking"
    authority = "authority"
    scarcity = "scarcity"
    manipulative_emotional_appeals = "manipulative_emotional_appeals"
    false_scarcity = "false_scarcity"
    deceptive_information = "deceptive_information"
    bait_and_switch = "bait_and_switch"
    exploitative_cult_tactics = "exploitative_cult_tactics"
    guilt_tripping = "guilt_tripping"
    fear_mongering = "fear_mongering"
    pressure_and_coercion = "pressure_and_coercion"
    exploiting_vulnerable_individuals = "exploiting_vulnerable_individuals"
    creating_dependency = "creating_dependency"
    misrepresentation_of_expertise = "misrepresentation_of_expertise"
    social_isolation = "social_isolation"
    overwhelming_information = "overwhelming_information"
    playing_on_identity = "playing_on_identity"
    financial_exploitation = "financial_exploitation"


class TacticsDetectedItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tactic: Tactic = Field(
        ...,
        description="One of 21 values from ENUMS.md → PersuasionTactic. Verbatim labels.",
    )
    evidence: str = Field(
        ..., description="Quoted span from the content that triggered this tactic."
    )
    confidence: confloat(ge=0.0, le=1.0)


class PersuasionFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tactics_detected: list[TacticsDetectedItem]
    intended_action: str = Field(
        ...,
        description="What the content is trying to get the user to do (e.g., 'buy supplement', 'share post', 'distrust vaccines').",
    )
    hidden_agenda: str | None = Field(
        None,
        description="Inferred motive beyond the surface ask, if any (e.g., 'affiliate revenue', 'political mobilization'). null if unclear.",
    )


class Verdict(StrEnum):
    supported = "supported"
    contradicted = "contradicted"
    unverifiable = "unverifiable"
    not_a_claim = "not_a_claim"


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    url: AnyUrl
    publisher: str | None = Field(None, description="WHO, CDC, Mayo Clinic, etc.")
    snippet: str | None = Field(None, description="Quoted relevant fragment from the source.")


class Claim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim: str = Field(..., description="Atomic factual claim extracted from content.")
    verdict: Verdict = Field(..., description="See ENUMS.md → FactCheckVerdict.")
    explanation: str | None = Field(None, description="Brief reason for the verdict.")
    sources: list[Source] | None = Field(
        None,
        description="RAG-retrieved sources backing the verdict. Empty for 'not_a_claim'.",
    )


class FactCheckFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claims: list[Claim] = Field(
        ...,
        description="Each factual claim extracted from the content, verified independently.",
    )


class SyntheticVerdict(StrEnum):
    likely_human = "likely_human"
    uncertain = "uncertain"
    likely_ai = "likely_ai"


class SourceVerdict(StrEnum):
    credible = "credible"
    mixed = "mixed"
    unreliable = "unreliable"
    unknown = "unknown"


class ProvenanceFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    synthetic_verdict: SyntheticVerdict = Field(..., description="See ENUMS.md → SyntheticVerdict.")
    source_verdict: SourceVerdict = Field(
        ...,
        description="Provenance Agent may upgrade or downgrade the L1 hardcoded reputation based on cross-referencing.",
    )
    reasoning: str = Field(
        ...,
        description="1-2 sentence rationale explaining the verdicts. Surfaced in 'Ask why' modal.",
    )


class Credibility(StrEnum):
    credible = "credible"
    mixed = "mixed"
    unreliable = "unreliable"
    unknown = "unknown"


class AlternativeSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl
    title: str
    publisher: str | None = None
    credibility: Credibility | None = None


class CounterPerspectiveFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    steelman: str = Field(
        ...,
        description="Best-faith opposing view to the content's claim, written as a coherent argument the user can engage with.",
    )
    alternative_sources: list[AlternativeSource] | None = Field(
        None, description="Higher-credibility sources offering a different angle."
    )


class SkippedAgent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent: AgentName
    reason: str


class ReasoningState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: SovereigntyScore
    dispatched_agents: list[AgentName] = Field(
        ..., description="Which L2 agents Coordinator decided to run for this content."
    )
    skipped_agents: list[SkippedAgent] | None = Field(
        None,
        description="Agents Coordinator deliberately skipped, with reason (e.g., 'meme → skip Fact-Check').",
    )
    persuasion: PersuasionFinding | None = None
    fact_check: FactCheckFinding | None = None
    provenance: ProvenanceFinding | None = None
    counter: CounterPerspectiveFinding | None = None


class SkippedAgent1(BaseModel):
    agent: AgentName
    reason: str


class CoordinatorDispatchedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["coordinator_dispatched"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    dispatched_agents: list[AgentName]
    skipped_agents: list[SkippedAgent1] | None = None


class AgentStartedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["agent_started"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    agent: AgentName


class AgentFinishedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["agent_finished"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    agent: AgentName
    finding: (
        PersuasionFinding | FactCheckFinding | ProvenanceFinding | CounterPerspectiveFinding
    ) = Field(
        ...,
        description="Concrete shape depends on agent: persuasion → PersuasionFinding, fact_check → FactCheckFinding, provenance → ProvenanceFinding, counter → CounterPerspectiveFinding.",
    )


class ScoreUpdateEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["score_update"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    score: SovereigntyScore


class FinalEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["final"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    state: ReasoningState


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        description="Stable error code (e.g., 'llm_timeout', 'rag_unavailable', 'invalid_input').",
    )
    message: str = Field(
        ...,
        description="Human-readable message. Safe to show in dev UI; production UI should map by code.",
    )


class ErrorEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["error"]
    session_id: UUID
    content_id: constr(min_length=1)
    timestamp: AwareDatetime
    agent: AgentName | None = Field(
        None, description="If error is scoped to one agent. Omit for global errors."
    )
    error: Error


class ReasoningEvent(
    RootModel[
        CoordinatorDispatchedEvent
        | AgentStartedEvent
        | AgentFinishedEvent
        | ScoreUpdateEvent
        | FinalEvent
        | ErrorEvent
    ]
):
    root: (
        CoordinatorDispatchedEvent
        | AgentStartedEvent
        | AgentFinishedEvent
        | ScoreUpdateEvent
        | FinalEvent
        | ErrorEvent
    ) = Field(
        ...,
        description="L2 → L3 contract. Each SSE event sent on GET /stream/{session_id} matches one of the event variants below. UI dispatches on the 'type' field. Enum values must match shared/ENUMS.md verbatim.",
        title="ReasoningEvent",
    )
